-- Synthetic schema for an isolated, disposable Postgres database only.
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN BYPASSRLS;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
CREATE SCHEMA auth;
GRANT USAGE ON SCHEMA auth TO anon, authenticated, service_role;
CREATE TABLE auth.users(id uuid PRIMARY KEY, email text);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
CREATE TABLE public.users(id uuid PRIMARY KEY REFERENCES auth.users(id), role text NOT NULL DEFAULT 'viewer', email text, full_name text, created_at timestamptz DEFAULT now());
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_self ON public.users FOR ALL TO authenticated
USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE TABLE public.contracts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text, status text,
  stage text DEFAULT 'draft', author text, expiry_date date, expiration_date date,
  updated_at timestamp, created_at timestamptz DEFAULT now(), contract_value numeric,
  content text, description text, category text, user_id uuid, created_by uuid,
  client_name text, client_email text, version text, file_url text, file_name text, file_type text
);
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
CREATE POLICY insecure_legacy_contracts ON public.contracts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TABLE public.contract_approval_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id bigint REFERENCES public.contracts(id) ON DELETE CASCADE,
  requester_id uuid REFERENCES auth.users(id), requester_email text, message text,
  status text DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(),
  approval_response text, approver_id uuid REFERENCES auth.users(id)
);
ALTER TABLE public.contract_approval_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY insecure_legacy_approvals ON public.contract_approval_requests FOR ALL TO authenticated USING (true) WITH CHECK (true);
