import { CheckCircle, Clock, AlertCircle } from 'lucide-react';

export const DEFAULT_PHASES = [
  {
    number: 1,
    nameKey: 'phaseTimeline.phase1.name',
    name: 'Tender Documents',
    descriptionKey: 'phaseTimeline.phase1.description',
    description: 'Proposal, bidding documents, and tender submissions',
    tasks: [
      { textKey: 'phaseManagement.tasks.prepareBid', text: 'Prepare bid package' },
      { textKey: 'phaseManagement.tasks.submitBid', text: 'Submit tender documents' },
    ],
  },
  {
    number: 2,
    nameKey: 'phaseTimeline.phase2.name',
    name: 'Legal Documents',
    descriptionKey: 'phaseTimeline.phase2.description',
    description: 'Decisions, assignments, and legal documentation',
    tasks: [
      { textKey: 'phaseManagement.tasks.legalApprovals', text: 'Obtain legal approvals' },
      { textKey: 'phaseManagement.tasks.assignmentDecision', text: 'Issue assignment decisions' },
    ],
  },
  {
    number: 3,
    nameKey: 'phaseTimeline.phase3.name',
    name: 'Joint Venture Documents',
    descriptionKey: 'phaseTimeline.phase3.description',
    description: 'Consortium agreements and linked documentation',
    tasks: [
      { textKey: 'phaseManagement.tasks.jvAgreement', text: 'Draft joint venture agreement' },
      { textKey: 'phaseManagement.tasks.jvSignoff', text: 'Collect partner signatures' },
    ],
  },
  {
    number: 4,
    nameKey: 'phaseTimeline.phase4.name',
    name: 'Contract & Appendices',
    descriptionKey: 'phaseTimeline.phase4.description',
    description: 'Main contract, amendments, and supplemental agreements',
    tasks: [
      { textKey: 'phaseManagement.tasks.contractDraft', text: 'Draft contract and appendices' },
      { textKey: 'phaseManagement.tasks.contractReview', text: 'Contract review and negotiation' },
      { textKey: 'phaseManagement.tasks.legalReview', text: 'Legal review and approval' },
      { textKey: 'phaseManagement.tasks.contractSign', text: 'Sign contract & amendments' },
      { textKey: 'phaseManagement.tasks.distributeCopies', text: 'Distribute signed copies' },
      { textKey: 'phaseManagement.tasks.archiveContract', text: 'Archive original contract' },
    ],
  },
  {
    number: 5,
    nameKey: 'phaseTimeline.phase5.name',
    name: 'Project Group Files',
    descriptionKey: 'phaseTimeline.phase5.description',
    description: 'Project team assignments and documentation',
    tasks: [
      { textKey: 'phaseManagement.tasks.assignTeam', text: 'Assign project team' },
      { textKey: 'phaseManagement.tasks.kickoffMeeting', text: 'Project kickoff meeting' },
      { textKey: 'phaseManagement.tasks.createProjectPlan', text: 'Create project plan' },
      { textKey: 'phaseManagement.tasks.setupCommunication', text: 'Setup communication channels' },
      { textKey: 'phaseManagement.tasks.internalDeliverables', text: 'Collect internal deliverables' },
      { textKey: 'phaseManagement.tasks.projectDocumentation', text: 'Complete project documentation' },
    ],
  },
  {
    number: 6,
    nameKey: 'phaseTimeline.phase6.name',
    name: 'Owner Payment Documents',
    descriptionKey: 'phaseTimeline.phase6.description',
    description: 'Settlement proposals, invoices, and payment records',
    tasks: [
      { textKey: 'phaseManagement.tasks.paymentProposal', text: 'Submit payment proposal' },
      { textKey: 'phaseManagement.tasks.invoiceGeneration', text: 'Invoice generation' },
      { textKey: 'phaseManagement.tasks.paymentTracking', text: 'Payment tracking' },
      { textKey: 'phaseManagement.tasks.paymentReconciliation', text: 'Payment reconciliation' },
      { textKey: 'phaseManagement.tasks.invoiceAndHandover', text: 'Issue invoices and handover' },
      { textKey: 'phaseManagement.tasks.financialClosure', text: 'Financial closure' },
    ],
  },
];

export const STATUS_CONFIG = {
  completed: { color: '#10b981', icon: CheckCircle, labelKey: 'phaseManagement.status.completed' },
  active: { color: '#3b82f6', icon: Clock, labelKey: 'phaseManagement.status.active' },
  pending: { color: '#6b7280', icon: Clock, labelKey: 'phaseManagement.status.pending' },
  delayed: { color: '#ef4444', icon: AlertCircle, labelKey: 'phaseManagement.status.delayed' },
};

export const TASK_TRANSLATION_MAP = {
  'Prepare bid package': 'phaseManagement.tasks.prepareBid',
  'Submit tender documents': 'phaseManagement.tasks.submitBid',
  'Obtain legal approvals': 'phaseManagement.tasks.legalApprovals',
  'Issue assignment decisions': 'phaseManagement.tasks.assignmentDecision',
  'Draft joint venture agreement': 'phaseManagement.tasks.jvAgreement',
  'Collect partner signatures': 'phaseManagement.tasks.jvSignoff',
  'Draft contract and appendices': 'phaseManagement.tasks.contractDraft',
  'Sign contract & amendments': 'phaseManagement.tasks.contractSign',
  'Assign project team': 'phaseManagement.tasks.assignTeam',
  'Collect internal deliverables': 'phaseManagement.tasks.internalDeliverables',
  'Submit payment proposal': 'phaseManagement.tasks.paymentProposal',
  'Issue invoices and handover': 'phaseManagement.tasks.invoiceAndHandover',
  'Initial client meeting': 'phaseManagement.tasks.initialClientMeeting',
  'Requirements gathering': 'phaseManagement.tasks.requirementsGathering',
  'Preliminary drawings': 'phaseManagement.tasks.preliminaryDrawings',
  'Client feedback session': 'phaseManagement.tasks.clientFeedback',
  'Design revisions': 'phaseManagement.tasks.designRevisions',
  'Final design approval': 'phaseManagement.tasks.finalDesignApproval',
  'Work commencement': 'phaseManagement.tasks.workCommencement',
  'Progress monitoring': 'phaseManagement.tasks.progressMonitoring',
  'Quality control checks': 'phaseManagement.tasks.qualityControl',
  'Client progress updates': 'phaseManagement.tasks.clientProgressUpdates',
  'Issue resolution': 'phaseManagement.tasks.issueResolution',
  'Final delivery & inspection': 'phaseManagement.tasks.finalDelivery',
  'Invoice generation': 'phaseManagement.tasks.invoiceGeneration',
  'Payment tracking': 'phaseManagement.tasks.paymentTracking',
  'Documentation compilation': 'phaseManagement.tasks.documentationCompilation',
  'Client satisfaction survey': 'phaseManagement.tasks.clientSatisfactionSurvey',
  'Lessons learned session': 'phaseManagement.tasks.lessonsLearned',
  'Contract closure': 'phaseManagement.tasks.contractClosure',
  'Contract review and negotiation': 'phaseManagement.tasks.contractReview',
  'Legal review and approval': 'phaseManagement.tasks.legalReview',
  'Distribute signed copies': 'phaseManagement.tasks.distributeCopies',
  'Archive original contract': 'phaseManagement.tasks.archiveContract',
  'Project kickoff meeting': 'phaseManagement.tasks.kickoffMeeting',
  'Create project plan': 'phaseManagement.tasks.createProjectPlan',
  'Setup communication channels': 'phaseManagement.tasks.setupCommunication',
  'Complete project documentation': 'phaseManagement.tasks.projectDocumentation',
  'Payment reconciliation': 'phaseManagement.tasks.paymentReconciliation',
  'Financial closure': 'phaseManagement.tasks.financialClosure',
};

export const getTaskTranslationKey = (taskText) => TASK_TRANSLATION_MAP[taskText] || null;

export const buttonStyle = (color = 'var(--primary)', disabled = false) => ({
  padding: '0.5rem 1rem',
  borderRadius: '6px',
  border: 'none',
  background: disabled ? '#9ca3af' : color,
  color: '#fff',
  cursor: disabled ? 'not-allowed' : 'pointer',
  display: 'flex',
  alignItems: 'center',
  gap: '0.5rem',
  fontSize: '0.9rem',
  transition: 'transform 0.2s, opacity 0.2s',
  opacity: disabled ? 0.6 : 1,
});
